### ISSUE TITLE
suggested improvements for documentation of df_apply()

### ISSUE THREAD

**Issue by rpruim** [adhamrishmawi1/NeglectR#13]
1. Looks like you are missing something in the description of `.filter()` -- what should this function return?
2. Which function gets `...`?
3. Don't define a wrapper around `is.numeric()` that doesn't modify what `is.numeric()` does.  (Just use `is.numeric()`)
4. Include an example demonstrating how `...` gets used.

**Comment by tjcontant** [comment]
###
